spring.datasource.url=jdbc:mysql://localhost:3306/tealedge
spring.datasource.username=root
spring.datasource.password=Srivathsav@27

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=4B6A8E3F2D1C5G7H9J0K2L4M6N8P0Q1R3S5T7U9V1W3X5Y7Z
google.client.id=859054408017-vvmqcdn72gm88jjvh7akrqopkp0k5jo1.apps.googleusercontent.com
app.cors.allowed-origins=https://teal-edge-learning.vercel.app
server.port=8082

